### ISSUE TITLE
Error in 'RunTestCases'

### ISSUE THREAD

**Issue by yuan-chengyi** [TardifLab/OptimizeIHMTimaging#1]
Hi,

When I ran the test function RunTestCases, I got an error.

> The unrecognized field name "satFlipAngle".
Error: BlochSimFlashSequence_v2 (line 111)
alpha = Params.satFlipAngle;
Error: qMT_test (line 108)
[sim_qMT(i), ~, ~] = BlochSimFlashSequence_v2(Params, 'GradientSpoiling',1,'ModelSpinDiffusion', 1);

I find that Params.satFlipAngle is not defined in the script qMT_test.
Could you please tell me what should i do to make the test function run?
Thank you!
Best regards!

Yuan.

**Comment by christopherrowley** [comment]
Hi Yuan,

Thanks for noticing this issue. I made a switch somewhat recently to using the flip angle of the saturation pulse 'satFlipAngle', instead of the B1rms, as this value seemed easier for people to obtain. 

I have pushed a fix for this now, and I also noticed an issue with the plots from the FLASH test cases. Let me know if you encounter any other issues!
